config/routes.rb
Rails.application.routes.draw do
  root 'client#reservation'
  get 'administration/action'
  get 'new_reservation', to: 'client#reservation'
  get 'my_reservation', to: 'client#new_reservation'
  get 'client_reservation', to: 'client#client_reservation'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/administration_controller.rb
class AdministrationController < ApplicationController
  def action
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/client_controller.rb
class ClientController < ApplicationController
  def reservation
  end

  def new_reservation
  end

  def client_reservation
  end
  

end

app/helpers/administration_helper.rb
module AdministrationHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/client_helper.rb
module ClientHelper
end

app/views/administration/action.html.erb
<div class="jumbotron">
  <h1 class="display-4">Administration</h1>


  <div class="form-check">
  <input class="form-check-input" type="checkbox" value="" id="defaultCheck1">
  <label class="form-check-label" for="defaultCheck1">
    Taux d'occupation
  </label>
</div>
  <div class="form-check">
  <input class="form-check-input" type="checkbox" value="" id="defaultCheck1">
  <label class="form-check-label" for="defaultCheck1">
    Revenu total journalier
  </label>
</div>
  <div class="form-check">
  <input class="form-check-input" type="checkbox" value="" id="defaultCheck1">
  <label class="form-check-label" for="defaultCheck1">
    Chambre a nettoyer
  </label>
</div>



  <hr class="my-4">
  <p></p>
  
  <p class="lead">
    <a class="btn btn-primary btn-lg" href="#" role="button">Générer les rapports</a>
    <a class="btn btn-success btn-lg" href="#" role="button">Voir les réservations</a>
    <a class="btn btn-light btn-lg" href="#" role="button">Chambres de l'hôtel</a>
  </p>
</div>

app/views/client/client_reservation.html.erb
<h1> Mes Réservations</h1>

<ul class="list-group">
  <li class="list-group-item">Réservation # 1 </li>
  <li class="list-group-item">Réservation # 2</li>
  <li class="list-group-item"> Réservation # 3</li>
  <li class="list-group-item"> Réservation # 4</li>
  <li class="list-group-item"> Réservation #5</li>
</ul>

app/views/client/new_reservation.html.erb
<h1>Réservation</h1>

<form>
<div class="row">
<div class="col-9">
  <div class="form-row">
    <div class="col">
      <input type="text" class="form-control" placeholder="Nom">
    </div>
    <div class="col">
      <input type="text" class="form-control" placeholder="Prénom">
    </div>
  </div>
 <div class="form-group">
    <label for="inputAddress">Téléphone</label>
    <input type="text" class="form-control" id="inputAddress" placeholder="514-555-5555">
  </div>

  <div class="form-group">
    <label for="exampleFormControlTextarea1">Ajouter une demande particulière. </label>
    <textarea class="form-control" id="exampleFormControlTextarea1" rows="3"></textarea>
  </div>

  <div class="form-row">
    <div class="form-group col-md-6">
      <label for="inputCity">Carte de crédit</label>
      <input type="text" class="form-control" id="inputCity">
    </div>
    <div class="form-group col-md-2">
      <label for="inputZip">CSV</label>
      <input type="text" class="form-control" id="inputZip">
    </div>
    <div class="form-group col-md-2">
      <label for="inputZip">EXP</label>
      <input type="text" class="form-control" id="inputZip">
    </div>
  </div>
  <div class="form-group">
    <div class="form-check">
      <input class="form-check-input" type="checkbox" id="gridCheck">
      <label class="form-check-label" for="gridCheck">
        Vue sur l'océan
      </label>
    </div>
  </div>
  <button type="submit" class="btn btn-primary">Réserver</button>


</div>
</div>

</form>

app/views/client/reservation.html.erb
<div class="jumbotron jumbotron-fluid">
  <div class="container">
    <h1 class="display-4">Nagano Comfort Inn </h1>
    <p class="lead">Plusieurs chambres disponibles</p>
  </div>
</div>
 
  <div class="album py-5 bg-light">
    <div class="container">

      <div class="row">
        <div class="col-md-4">
          <div class="card mb-4 shadow-sm">
            <svg class="bd-placeholder-img card-img-top" width="100%" height="225" xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid slice" focusable="false" role="img" aria-label="Placeholder: Thumbnail"><title>Placeholder</title><rect width="100%" height="100%" fill="#55595c"/><text x="50%" y="50%" fill="#eceeef" dy=".3em">Chambre lit simple</text></svg>
            <div class="card-body">
              <p class="card-text">Chambre lit simple. </p>
              <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                 <button type="button" class="btn btn-sm btn-outline-secondary">Voir</button>
                  <button type="button" class="btn btn-sm btn-outline-secondary">Réserver</button>
                </div>
                <small class="text-muted">Courte description de la chambre</small>
              </div>
            </div>
          </div>
        </div>
        <div class="col-md-4">
          <div class="card mb-4 shadow-sm">
            <svg class="bd-placeholder-img card-img-top" width="100%" height="225" xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid slice" focusable="false" role="img" aria-label="Placeholder: Thumbnail"><title>Placeholder</title><rect width="100%" height="100%" fill="#55595c"/><text x="50%" y="50%" fill="#eceeef" dy=".3em">Chambre lit double</text></svg>
            <div class="card-body">
              <p class="card-text">Chambre lit double</p>
              <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
             <button type="button" class="btn btn-sm btn-outline-secondary">Voir</button>
                  <button type="button" class="btn btn-sm btn-outline-secondary">Réserver</button>
                </div>
                <small class="text-muted">Courte description de la chambre</small>
              </div>
            </div>
          </div>
        </div>
        <div class="col-md-4">
          <div class="card mb-4 shadow-sm">
            <svg class="bd-placeholder-img card-img-top" width="100%" height="225" xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid slice" focusable="false" role="img" aria-label="Placeholder: Thumbnail"><title>Placeholder</title><rect width="100%" height="100%" fill="#55595c"/><text x="50%" y="50%" fill="#eceeef" dy=".3em">Chambre exécutive</text></svg>
            <div class="card-body">
              <p class="card-text">Chambre exécutive</p>
              <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                  <button type="button" class="btn btn-sm btn-outline-secondary">Voir</button>
                  <button type="button" class="btn btn-sm btn-outline-secondary">Réserver</button>
                </div>
               <small class="text-muted">Courte description de la chambre</small>
              </div>
            </div>
          </div>
        </div>   
             <div class="col-md-4">
          <div class="card mb-4 shadow-sm">
            <svg class="bd-placeholder-img card-img-top" width="100%" height="225" xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid slice" focusable="false" role="img" aria-label="Placeholder: Thumbnail"><title>Placeholder</title><rect width="100%" height="100%" fill="#55595c"/><text x="50%" y="50%" fill="#eceeef" dy=".3em">Suite présidentielle</text></svg>
            <div class="card-body">
              <p class="card-text">Suite présidentielle</p>
              <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                  <button type="button" class="btn btn-sm btn-outline-secondary">Voir</button>
                  <button type="button" class="btn btn-sm btn-outline-secondary">Réserver</button>
                </div>
               <small class="text-muted">Courte description de la chambre</small>
              </div>
            </div>
          </div>
        </div>   
      

      
      </div>
    </div>
  </div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">Nagano Comfort Inn </a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
    <li class="nav-item <%= 'active' if request.path == root_path %>">
        <%= link_to 'Accueil', root_path, class:"nav-link" %>      
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Réservation
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                      
        <%= link_to 'Voir ses réservations', client_reservation_path, class:"dropdown-item"%>      
    
          <div class="dropdown-divider"></div>

         <%= link_to 'Prendre une réservation', my_reservation_path, class:"dropdown-item"%>

        </div>
          <li class="nav-item <%= 'active' if request.path == root_path %>">
        <%= link_to 'Administration', administration_action_path, class:"nav-link" %>      
      </li>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0">

      <div class="form-group row">
  <label for="example-date-input" class="col-2 col-form-label">Arrivée</label>
  <div class="col-10">
    <input class="form-control" type="date" value="2011-08-19" id="example-date-input">
  </div>
</div>
        <div class="form-group row">
          <label for="example-date-input" class="col-2 col-form-label">Départ</label>
            <div class="col-10">
            <input class="form-control" type="date" value="2011-08-19" id="example-date-input">
            </div>
        </div>
      
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Recherche</button>
    </form>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NaganoComfortInn</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%= render 'layouts/navbar'%>
   <div class="container">
    <%= yield %>
   </div>
  </body>
</html>